
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JButton;
/**
 *
 * @author KENZIE
 */
public class Procal extends javax.swing.JFrame {

    /**
     * Creates new form Procal
     */
    public Procal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TextInput = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        AllClearButton = new javax.swing.JButton();
        NotEqualButton = new javax.swing.JButton();
        MultiplicationButton = new javax.swing.JButton();
        EqualsButton = new javax.swing.JButton();
        Parenthesis = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        LTButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        ANDButton = new javax.swing.JButton();
        DivideButton = new javax.swing.JButton();
        ORButton = new javax.swing.JButton();
        AdditionButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        LTEQButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        BitwiseButton = new javax.swing.JButton();
        SubtrationButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        GTButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        NotButton = new javax.swing.JButton();
        EqualButton = new javax.swing.JButton();
        ZeroButton = new javax.swing.JButton();
        DeciButton = new javax.swing.JButton();
        GTEQButton = new javax.swing.JButton();
        ModulusButton = new javax.swing.JButton();

        jButton13.setText("jButton1");
        jButton13.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton13.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton13.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton14.setText("jButton1");
        jButton14.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton14.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton14.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton15.setText("jButton1");
        jButton15.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton15.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton15.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton16.setText("jButton1");
        jButton16.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton16.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton16.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton17.setText("jButton1");
        jButton17.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton17.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton17.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton18.setText("jButton1");
        jButton18.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton18.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton18.setPreferredSize(new java.awt.Dimension(29, 25));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        TextInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 4, true));

        DeleteButton.setBackground(new java.awt.Color(102, 0, 0));
        DeleteButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("DEL");
        DeleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        DeleteButton.setMaximumSize(new java.awt.Dimension(29, 25));
        DeleteButton.setMinimumSize(new java.awt.Dimension(29, 25));
        DeleteButton.setPreferredSize(new java.awt.Dimension(29, 25));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteInput(evt);
            }
        });

        AllClearButton.setBackground(new java.awt.Color(102, 0, 0));
        AllClearButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        AllClearButton.setForeground(new java.awt.Color(255, 255, 255));
        AllClearButton.setText("AC");
        AllClearButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        AllClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllClear(evt);
            }
        });

        NotEqualButton.setBackground(new java.awt.Color(255, 51, 0));
        NotEqualButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        NotEqualButton.setForeground(new java.awt.Color(255, 255, 255));
        NotEqualButton.setText("!=");
        NotEqualButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        NotEqualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        MultiplicationButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        MultiplicationButton.setText("*");
        MultiplicationButton.setMaximumSize(new java.awt.Dimension(29, 25));
        MultiplicationButton.setMinimumSize(new java.awt.Dimension(29, 25));
        MultiplicationButton.setPreferredSize(new java.awt.Dimension(29, 25));
        MultiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        EqualsButton.setBackground(new java.awt.Color(255, 51, 0));
        EqualsButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        EqualsButton.setForeground(new java.awt.Color(255, 255, 255));
        EqualsButton.setText("==");
        EqualsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        EqualsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        Parenthesis.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        Parenthesis.setText("()");
        Parenthesis.setMaximumSize(new java.awt.Dimension(29, 25));
        Parenthesis.setMinimumSize(new java.awt.Dimension(29, 25));
        Parenthesis.setPreferredSize(new java.awt.Dimension(29, 25));
        Parenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParthesisAction(evt);
            }
        });

        EightButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        EightButton.setText("8");
        EightButton.setMaximumSize(new java.awt.Dimension(29, 25));
        EightButton.setMinimumSize(new java.awt.Dimension(29, 25));
        EightButton.setPreferredSize(new java.awt.Dimension(29, 25));
        EightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        SevenButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        SevenButton.setText("7");
        SevenButton.setMaximumSize(new java.awt.Dimension(29, 25));
        SevenButton.setMinimumSize(new java.awt.Dimension(29, 25));
        SevenButton.setPreferredSize(new java.awt.Dimension(29, 25));
        SevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        LTButton.setBackground(new java.awt.Color(255, 51, 0));
        LTButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        LTButton.setForeground(new java.awt.Color(255, 255, 255));
        LTButton.setText("<");
        LTButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        LTButton.setMaximumSize(new java.awt.Dimension(29, 25));
        LTButton.setMinimumSize(new java.awt.Dimension(29, 25));
        LTButton.setPreferredSize(new java.awt.Dimension(29, 25));
        LTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        NineButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        NineButton.setText("9");
        NineButton.setMaximumSize(new java.awt.Dimension(29, 25));
        NineButton.setMinimumSize(new java.awt.Dimension(29, 25));
        NineButton.setPreferredSize(new java.awt.Dimension(29, 25));
        NineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        ANDButton.setBackground(new java.awt.Color(204, 0, 153));
        ANDButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ANDButton.setForeground(new java.awt.Color(255, 255, 255));
        ANDButton.setText("&&");
        ANDButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        ANDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        DivideButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        DivideButton.setText("/");
        DivideButton.setMaximumSize(new java.awt.Dimension(29, 25));
        DivideButton.setMinimumSize(new java.awt.Dimension(29, 25));
        DivideButton.setPreferredSize(new java.awt.Dimension(29, 25));
        DivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        ORButton.setBackground(new java.awt.Color(204, 0, 153));
        ORButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ORButton.setForeground(new java.awt.Color(255, 255, 255));
        ORButton.setText("||");
        ORButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        ORButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        AdditionButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        AdditionButton.setText("+");
        AdditionButton.setMaximumSize(new java.awt.Dimension(29, 25));
        AdditionButton.setMinimumSize(new java.awt.Dimension(29, 25));
        AdditionButton.setPreferredSize(new java.awt.Dimension(29, 25));
        AdditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        FiveButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        FiveButton.setText("5");
        FiveButton.setMaximumSize(new java.awt.Dimension(29, 25));
        FiveButton.setMinimumSize(new java.awt.Dimension(29, 25));
        FiveButton.setPreferredSize(new java.awt.Dimension(29, 25));
        FiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        FourButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        FourButton.setText("4");
        FourButton.setMaximumSize(new java.awt.Dimension(29, 25));
        FourButton.setMinimumSize(new java.awt.Dimension(29, 25));
        FourButton.setPreferredSize(new java.awt.Dimension(29, 25));
        FourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        LTEQButton.setBackground(new java.awt.Color(255, 51, 0));
        LTEQButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        LTEQButton.setForeground(new java.awt.Color(255, 255, 255));
        LTEQButton.setText("<=");
        LTEQButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        LTEQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        SixButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        SixButton.setText("6");
        SixButton.setMaximumSize(new java.awt.Dimension(29, 25));
        SixButton.setMinimumSize(new java.awt.Dimension(29, 25));
        SixButton.setPreferredSize(new java.awt.Dimension(29, 25));
        SixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        BitwiseButton.setBackground(new java.awt.Color(204, 0, 153));
        BitwiseButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        BitwiseButton.setForeground(new java.awt.Color(255, 255, 255));
        BitwiseButton.setText("^");
        BitwiseButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        BitwiseButton.setMaximumSize(new java.awt.Dimension(29, 25));
        BitwiseButton.setMinimumSize(new java.awt.Dimension(29, 25));
        BitwiseButton.setPreferredSize(new java.awt.Dimension(29, 25));
        BitwiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        SubtrationButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        SubtrationButton.setText("-");
        SubtrationButton.setActionCommand("-");
        SubtrationButton.setMaximumSize(new java.awt.Dimension(29, 25));
        SubtrationButton.setMinimumSize(new java.awt.Dimension(29, 25));
        SubtrationButton.setPreferredSize(new java.awt.Dimension(29, 25));
        SubtrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        TwoButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        TwoButton.setText("2");
        TwoButton.setMaximumSize(new java.awt.Dimension(29, 25));
        TwoButton.setMinimumSize(new java.awt.Dimension(29, 25));
        TwoButton.setPreferredSize(new java.awt.Dimension(29, 25));
        TwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        OneButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        OneButton.setText("1");
        OneButton.setMaximumSize(new java.awt.Dimension(29, 25));
        OneButton.setMinimumSize(new java.awt.Dimension(29, 25));
        OneButton.setPreferredSize(new java.awt.Dimension(29, 25));
        OneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        GTButton.setBackground(new java.awt.Color(255, 51, 0));
        GTButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        GTButton.setForeground(new java.awt.Color(255, 255, 255));
        GTButton.setText(">");
        GTButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        GTButton.setMaximumSize(new java.awt.Dimension(29, 25));
        GTButton.setMinimumSize(new java.awt.Dimension(29, 25));
        GTButton.setPreferredSize(new java.awt.Dimension(29, 25));
        GTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        ThreeButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ThreeButton.setText("3");
        ThreeButton.setMaximumSize(new java.awt.Dimension(29, 25));
        ThreeButton.setMinimumSize(new java.awt.Dimension(29, 25));
        ThreeButton.setPreferredSize(new java.awt.Dimension(29, 25));
        ThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        NotButton.setBackground(new java.awt.Color(204, 0, 153));
        NotButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        NotButton.setForeground(new java.awt.Color(255, 255, 255));
        NotButton.setText("!");
        NotButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        NotButton.setMaximumSize(new java.awt.Dimension(29, 25));
        NotButton.setMinimumSize(new java.awt.Dimension(29, 25));
        NotButton.setPreferredSize(new java.awt.Dimension(29, 25));
        NotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        EqualButton.setBackground(new java.awt.Color(0, 0, 102));
        EqualButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        EqualButton.setForeground(new java.awt.Color(255, 255, 255));
        EqualButton.setText("=");
        EqualButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true));
        EqualButton.setMaximumSize(new java.awt.Dimension(29, 25));
        EqualButton.setMinimumSize(new java.awt.Dimension(29, 25));
        EqualButton.setPreferredSize(new java.awt.Dimension(29, 25));
        EqualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueOutput(evt);
            }
        });

        ZeroButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ZeroButton.setText("0");
        ZeroButton.setMaximumSize(new java.awt.Dimension(29, 25));
        ZeroButton.setMinimumSize(new java.awt.Dimension(29, 25));
        ZeroButton.setPreferredSize(new java.awt.Dimension(29, 25));
        ZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        DeciButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        DeciButton.setText(".");
        DeciButton.setMaximumSize(new java.awt.Dimension(29, 25));
        DeciButton.setMinimumSize(new java.awt.Dimension(29, 25));
        DeciButton.setPreferredSize(new java.awt.Dimension(29, 25));
        DeciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        GTEQButton.setBackground(new java.awt.Color(255, 51, 0));
        GTEQButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        GTEQButton.setForeground(new java.awt.Color(255, 255, 255));
        GTEQButton.setText(">=");
        GTEQButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        GTEQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        ModulusButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ModulusButton.setText("%");
        ModulusButton.setMaximumSize(new java.awt.Dimension(29, 25));
        ModulusButton.setMinimumSize(new java.awt.Dimension(29, 25));
        ModulusButton.setPreferredSize(new java.awt.Dimension(29, 25));
        ModulusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAction(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AllClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MultiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NotEqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Parenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ANDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LTEQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ORButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BitwiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubtrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DeciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModulusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GTEQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotEqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTEQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ORButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BitwiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubtrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GTEQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModulusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAction
        JButton booth = (JButton) evt.getSource();
        TextInput.setText(TextInput.getText() + booth.getText());
    }//GEN-LAST:event_ButtonAction

    private boolean isParenthesisEqual(String text){
        int balanceFactor = 0;
        for(int i = 0; i<text.length(); i++){
            if(text.charAt(i) == '(')
                balanceFactor++;
            if(text.charAt(i) == ')')
                balanceFactor--;
        }
        return balanceFactor == 0;
    }
    private void ParthesisAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParthesisAction
       String textInputText = TextInput.getText();
       if(textInputText.isEmpty()){
           TextInput.setText("(");
           return;
       }
       Boolean isParenEqual = isParenthesisEqual(textInputText);
       String prtlogic = TextInput.getText().substring(TextInput.getText().length()-1);
       if(isParenEqual){
           TextInput.setText(TextInput.getText() + "*(");
       } else if(prtlogic.matches("[0-9]") && !isParenEqual){
           TextInput.setText(TextInput.getText() + ")");
       } else if(prtlogic.matches("[^0-9\\)]") && !isParenEqual){
            TextInput.setText(TextInput.getText() + "(");
       } else {
            TextInput.setText(TextInput.getText() + ")");

       }
    }//GEN-LAST:event_ParthesisAction

    private void AllClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllClear
        TextInput.setText("");
    }//GEN-LAST:event_AllClear

    private void DeleteInput(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteInput
        TextInput.setText(TextInput.getText().substring(0,TextInput.getText().length()-1));
    }//GEN-LAST:event_DeleteInput

//    private String[] removeEmpty(String[] str){
//        int strLength = 0;
//        for(String s: str){
//            if(s.isEmpty())
//                continue;
//            strLength++;
//        }
//        String[] newStr = new String[strLength];
//        int strIndex = 0;
//        
//        for(String s: str){
//            if(s.isEmpty())
//                continue;
//            newStr[strIndex] = s;
//            strIndex++;
//        }
//        return newStr;
//    }
    private void ValueOutput(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueOutput
        String Artm = TextInput.getText();
        ArrayList<String> n = new ArrayList<>(Arrays.asList(Artm.split("[^0-9]")));
        ArrayList<String> o = new ArrayList<>(Arrays.asList(Artm.split("[0-9]")));
        
        // Removes all empty items
        n.removeAll(Arrays.asList(""));
        o.removeAll(Arrays.asList(""));
        
        
        while(n.size()> 1){
            
        }

    }//GEN-LAST:event_ValueOutput

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANDButton;
    private javax.swing.JButton AdditionButton;
    private javax.swing.JButton AllClearButton;
    private javax.swing.JButton BitwiseButton;
    private javax.swing.JButton DeciButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DivideButton;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton EqualButton;
    private javax.swing.JButton EqualsButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JButton FourButton;
    private javax.swing.JButton GTButton;
    private javax.swing.JButton GTEQButton;
    private javax.swing.JButton LTButton;
    private javax.swing.JButton LTEQButton;
    private javax.swing.JButton ModulusButton;
    private javax.swing.JButton MultiplicationButton;
    private javax.swing.JButton NineButton;
    private javax.swing.JButton NotButton;
    private javax.swing.JButton NotEqualButton;
    private javax.swing.JButton ORButton;
    private javax.swing.JButton OneButton;
    private javax.swing.JButton Parenthesis;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JButton SubtrationButton;
    private javax.swing.JTextField TextInput;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
